### ISSUE TITLE
The node type RestProperty has been renamed to RestElement

### ISSUE THREAD

**Issue by catb0t** [LiveSplit/LiveSplitOne#141]
seems like a deprecation warning
```
Trace: The node type RestProperty has been renamed to RestElement
    at Object.isRestProperty (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/types/lib/validators/generated/index.js:4176:11)
    at DestructuringTransformer.pushObjectPattern (/home/cat/Sync/projects/git/livesplitone/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:197:15)
    at DestructuringTransformer.push (/home/cat/Sync/projects/git/livesplitone/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:108:14)
    at DestructuringTransformer.init (/home/cat/Sync/projects/git/livesplitone/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:317:12)
    at PluginPass.VariableDeclaration (/home/cat/Sync/projects/git/livesplitone/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:468:27)
    at newFn (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/home/cat/Sync/projects/git/livesplitone/node_modules/@babel/traverse/lib/context.js:90:19)
```

**Comment by CryZe** [comment]
Yeah I've seen that. It started appearing once I updated some of the dependencies. This however doesn't seem to be caused by any of LiveSplit One's code directly. Maybe some dependency needs to get updated again? I honestly don't know. If someone knows, that would be appreciated.

**Comment by catb0t** [comment]
I can try to look a little harder at it later, it seems to be babel_traverse I guess.

**Comment by catb0t** [comment]
I think it was caused by this: https://github.com/babel/babel/pull/5394

This project seems to use `@babel/types == 7.30` but `babel-types == 6.26.0`, 6.26 is the latest version of babel-types which is really bizarre, maybe this should be filed against [babel/babel](https://github.com/babel/babel/)

**Comment by yairEO** [comment]
I deleted the folder for that plugin in `node_modules` and installed [`@babel/plugin-transform-destructuring`](https://babeljs.io/docs/en/babel-plugin-transform-destructuring) instead and now I don't get errors anymore.
